ci:
    autoupdate_schedule: monthly
exclude: '^(outputs/|src/movement_figures/fonts/)'
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-yaml
          - id: check-toml
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: trailing-whitespace
          - id: name-tests-test
            args: ["--pytest-test-first"]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.15.15
      hooks:
          - id: ruff
          - id: ruff-format
    - repo: https://github.com/codespell-project/codespell
      rev: v2.4.2
      hooks:
          - id: codespell
